In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.sample(5)

        brand  km_driven    fuel        owner  selling_price
978   Hyundai      80000  Diesel  First Owner         650000
7961   Maruti     120000  Diesel  First Owner         530000
8008   Maruti      40000  Petrol  First Owner         382000
2576   Maruti      14000  Petrol  First Owner         380000
3968   Maruti      70000  Petrol  First Owner         650000

In [4]:
df = df.iloc[: , 2:]

In [6]:
df.sample(5)

        fuel        owner  selling_price
779   Petrol  First Owner         500000
1006  Diesel  First Owner         900000
7960  Diesel  First Owner         730000
4779  Petrol  First Owner         260000
4615  Diesel  First Owner         800000